
  CREATE UNIQUE INDEX "TAN"."SYS_C005467" ON "TAN"."PROECT_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROECT_DETAILS
--------------------------------------------------------

  ALTER TABLE "TAN"."PROECT_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."PROECT_DETAILS" MODIFY ("LOGIN" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."PROECT_DETAILS" MODIFY ("HEADNAME" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."PROECT_DETAILS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."PROECT_DETAILS" MODIFY ("PROECT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."PROECT_DETAILS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROECT_DETAILS
--------------------------------------------------------

  ALTER TABLE "TAN"."PROECT_DETAILS" ADD CONSTRAINT "PROECT_DETAIL_PRO_FK" FOREIGN KEY ("PROECT_ID")
	  REFERENCES "TAN"."PROECTS" ("IDPROECT") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "TAN"."PROECT_DETAILS" ADD CONSTRAINT "PROECT_DETAIL_USERS_FK" FOREIGN KEY ("LOGIN")
	  REFERENCES "TAN"."USERS" ("USER_LOGIN") ON DELETE CASCADE ENABLE;


2-------------------------------------------------------------

CREATE UNIQUE INDEX "TAN"."SYS_C005461" ON "TAN"."PROECTS" ("IDPROECT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROECTS
--------------------------------------------------------

  ALTER TABLE "TAN"."PROECTS" MODIFY ("IDPROECT" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."PROECTS" MODIFY ("PROECTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."PROECTS" MODIFY ("PROECTDATE" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."PROECTS" ADD PRIMARY KEY ("IDPROECT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;

3-----------------------------------------------------------
CREATE UNIQUE INDEX "TAN"."SYS_C005457" ON "TAN"."USERS" ("USER_LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "TAN"."USERS" MODIFY ("USER_LOGIN" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."USERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."USERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."USERS" MODIFY ("USER_ROLE" NOT NULL ENABLE);
 
  ALTER TABLE "TAN"."USERS" ADD PRIMARY KEY ("USER_LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
4----------------------------------------------------------
