CREATE TABLE "TAN"."PROECT_DETAILS" 
   (	"ID" VARCHAR2(50 CHAR), 
	"LOGIN" VARCHAR2(20 CHAR), 
	"HEADNAME" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"PROECT_ID" VARCHAR2(50 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TAN.PROECT_DETAILS
SET DEFINE OFF;
Insert into TAN.PROECT_DETAILS (ID,LOGIN,HEADNAME,DESCRIPTION,PROECT_ID) values ('lsjuyeb365','LLada','Sobranie','qqhgy7gf7yskdgvlsiud','gen12lad');

--------------------------------------------------------------

CREATE TABLE "TAN"."PROECTS" 
   (	"IDPROECT" VARCHAR2(50 CHAR), 
	"PROECTNAME" VARCHAR2(50 CHAR), 
	"PROECTDATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TAN.PROECTS
SET DEFINE OFF;
Insert into TAN.PROECTS (IDPROECT,PROECTNAME,PROECTDATE) values ('gen12lad','MisterKPI',to_timestamp('24.01.17 01:35:52,828000000','DD.MM.RR HH24:MI:SS,FF'));

-----------------------------------------------------------
CREATE TABLE "TAN"."USERS" 
   (	"USER_LOGIN" VARCHAR2(20 CHAR), 
	"FIRSTNAME" VARCHAR2(20 CHAR), 
	"LASTNAME" VARCHAR2(20 CHAR), 
	"PASSWORD" VARCHAR2(20 CHAR), 
	"USER_ROLE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TAN.USERS
SET DEFINE OFF;
Insert into TAN.USERS (USER_LOGIN,FIRSTNAME,LASTNAME,PASSWORD,USER_ROLE) values ('Lada12','gfhfh','tyhrthr','llllada','USER');
Insert into TAN.USERS (USER_LOGIN,FIRSTNAME,LASTNAME,PASSWORD,USER_ROLE) values ('Llada','fgdnh','fhynyg','12345','USER');
Insert into TAN.USERS (USER_LOGIN,FIRSTNAME,LASTNAME,PASSWORD,USER_ROLE) values ('LLada','Lada','Efanova','Lada12','User');
---------------------------------------------------------
CREATE OR REPLACE FORCE VIEW "TAN"."ONEPROJECT" ("IDPROJECT", "PROJECTNAME", "PROJECTDATE", "DETAILID", "CREATORLOGIN", "HEADNAME", "DESCRIPTION") AS 
  Select proects.IDPROECT IDPROJECT,
proects.PROECTNAME PROJECTNAME,
proects.PROECTDATE PROJECTDATE,
proect_details.ID DETAILID,
proect_details.LOGIN CREATORLOGIN,
proect_details.HEADNAME HEADNAME,
proect_details.DESCRIPTION DESCRIPTION
From PROECTS inner join PROECT_DETAILS on
PROECTS.idproect = proect_details.proect_id;
REM INSERTING into TAN.ONEPROJECT
SET DEFINE OFF;
Insert into TAN.ONEPROJECT (IDPROJECT,PROJECTNAME,PROJECTDATE,DETAILID,CREATORLOGIN,HEADNAME,DESCRIPTION) values ('gen12lad','MisterKPI',to_timestamp('24.01.17 01:35:52,828000000','DD.MM.RR HH24:MI:SS,FF'),'lsjuyeb365','LLada','Sobranie','qqhgy7gf7yskdgvlsiud');
